name: CI/CD Pipeline for FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Checkout le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuration de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure CLI
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry (ACR)s
      - name: Log in to ACR
        run: |
          az acr login --name acrauthtemplate

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t authimages:latest .

      - name: tag Docker image
        run: |
          docker tag authimages:latest authimageslucasz.azurecr.io/authimages:latest

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push authimageslucasz.azurecr.io/authimages:latest

      # # Déployer sur Azure Web App
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: weatherappplanname
      #     images: weatherapplucasz.azurecr.io/weatherapp:latest
